rm ~/Desktop/argumentation-framework-clustering/thesis/main-blx.bib
rm ~/Desktop/argumentation-framework-clustering/thesis/main-example.bib
rm ~/Desktop/argumentation-framework-clustering/thesis/main.aux
rm ~/Desktop/argumentation-framework-clustering/thesis/main.lof
rm ~/Desktop/argumentation-framework-clustering/thesis/main.log
rm ~/Desktop/argumentation-framework-clustering/thesis/main.lot
rm ~/Desktop/argumentation-framework-clustering/thesis/main.run.xml
rm ~/Desktop/argumentation-framework-clustering/thesis/main.toc
rm ~/Desktop/argumentation-framework-clustering/thesis/main.bbl
rm ~/Desktop/argumentation-framework-clustering/thesis/main.blg
rm ~/Desktop/argumentation-framework-clustering/thesis/main.fdb_latexmk
rm ~/Desktop/argumentation-framework-clustering/thesis/main.fls
rm ~/Desktop/argumentation-framework-clustering/thesis/main.out
rm ~/Desktop/argumentation-framework-clustering/thesis/main.bcf
rm ~/Desktop/argumentation-framework-clustering/thesis/helper/*.aux
rm ~/Desktop/argumentation-framework-clustering/thesis/docs/*.aux